<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ledgerly.Client</RootNamespace>
    <AssemblyName>Coalesce.Client</AssemblyName>
    <AssemblyTitle>Coalesce.ERP.CRM Client</AssemblyTitle>
    <Product>Coalesce.ERP.CRM</Product>
    <ApplicationIcon />
    <SupportedOSPlatform>windows7.0</SupportedOSPlatform>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ledgerly.Shared\Ledgerly.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
